In [1]:
#importing libraries

#for mathematical calculations
import numpy as np 
#for plotting charts
import matplotlib.pyplot as plt
#for directory operations
import pandas as pd


In [3]:
#import dataset
dataset = pd.read_csv("C:/Users/Nill/Desktop/Machine Learning A-Z/Part 1 - Data Preprocessing/Section 2 -Part 1 - Data Preprocessing -/Data.csv")

In [6]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [11]:
#here we create independent variable vector
#we take all the rows and column except the last one (first ':' is for row and second is for column)
X = dataset.iloc[:,:-1].values

In [9]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [13]:
#here we create dependent variable vector
#we take all rows but only one column that has index of 3
Y = dataset.iloc[:,3].values

In [14]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [16]:
#handling missing data

#library for taking care of missing data
from sklearn.preprocessing import Imputer 

#creatinag an object of the above class
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)

#fit the above imputer object to our data X or matrix of feature x
imputer = imputer.fit(X[:,1:3]) #fit only in column 1 and 2 (here in 1:3, upper bound is not included)

#replace missing data of matrix X by mean of the column
X[:,1:3] = imputer.transform(X[:,1:3])

In [17]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [22]:
#Encoding categorical Data

#in the dataset, country contains 3 catgeories (france, spain, germany) and purchased contains two(yes, no)
#we encode text in above categories as numbers

#library for encoding
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()

#apply labeEncoder object on our column
X[:,0] = labelencoder_X.fit_transform(X[:,0])

#output contains country as encoded values
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [36]:
#categorical encoding could lead us to wrong results as it can imply that one value could be greater than the other(not in this case)

#dummy encoding with oneHotEncoder
from sklearn.preprocessing import OneHotEncoder

#dummy encoding does something like this
#coutry              France Germany Spain
#-----------------------------------------
#france                 1     0       0
#spain                  0     0       1 
#Germany                0     1       0
#spain                  0     0       1 
#Germany                0     1       0


#specify which column should be onehotencode category
onehotencoder = OneHotEncoder(categorical_features = [0])

#fit it to matrix X
X = onehotencoder.fit_transform(X).toarray()

In [25]:
print(X)

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   4.40000000e+01
    7.20000000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   2.70000000e+01
    4.80000000e+04]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   3.00000000e+01
    5.40000000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   3.80000000e+01
    6.10000000e+04]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   4.00000000e+01
    6.37777778e+04]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   3.50000000e+01
    5.80000000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   3.87777778e+01
    5.20000000e+04]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   4.80000000e+01
    7.90000000e+04]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   5.00000000e+01
    8.30000000e+04]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   3.70000000e+01
    6.70000000e+04]]


In [28]:
#dummy encoding the dependent variable(purchased column)

labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

#look at y
print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [29]:
#splitting the dataset

#library for splitting
from sklearn.cross_validation import train_test_split

#test size is 0.2(20% of the dataset) and random_state is for random sampling
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)


C:\Users\Nill\Miniconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [33]:
#since there is huge difference between values in age and salary, feature scaling is done (they are not is same scale)
#two ways are standardisation and normalization

#library for feature scaling
from sklearn.preprocessing import StandardScaler

#create StandaradScaler object
sc_X = StandardScaler()

#fit it to the train dataset
X_train = sc_X.fit_transform(X_train)
#no need to fit to the test set (since its already fitted in train set)
X_test = sc_X.transform(X_test)


In [34]:
#now the values will be much lower
print(X_train)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
