In [ ]:
#a multiple linear regression attempts to model relatioship between two or more explanatory variable

#The equation can be moulded as y = b0 + b1X1 + b2X2 + .... + bnXn

In [1]:
#data preprocessing part

#importing libraries
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

#import dataset
dataset = pd.read_csv("C:/Users/Nill/Desktop/Machine Learning A-Z/Part 2 - Regression/Section 5 - Multiple Linear Regression/50_Startups.csv")
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [2]:
#we create independent and dependent variable vector or feature matrix

#independet variable (number of years) or matrix of features (-1 removes last column of the dataset)
X = dataset.iloc[:, :-1].values

#get the dependent variable (salary) that has an index of 1
Y = dataset.iloc[:, 4].values

In [3]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [4]:
#Encoding categorical Data

#the dataset, country contains catgeories (New York, floride, california)
#we encode text in above categories as numbers

#library for encoding
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()

#apply labeEncoder object on our column (3 is the index of categorical column)
X[:,3] = labelencoder_X.fit_transform(X[:,3])

#output contains country as encoded values
print(X)

[[165349.2 136897.8 471784.1 2]
 [162597.7 151377.59 443898.53 0]
 [153441.51 101145.55 407934.54 1]
 [144372.41 118671.85 383199.62 2]
 [142107.34 91391.77 366168.42 1]
 [131876.9 99814.71 362861.36 2]
 [134615.46 147198.87 127716.82 0]
 [130298.13 145530.06 323876.68 1]
 [120542.52 148718.95 311613.29 2]
 [123334.88 108679.17 304981.62 0]
 [101913.08 110594.11 229160.95 1]
 [100671.96 91790.61 249744.55 0]
 [93863.75 127320.38 249839.44 1]
 [91992.39 135495.07 252664.93 0]
 [119943.24 156547.42 256512.92 1]
 [114523.61 122616.84 261776.23 2]
 [78013.11 121597.55 264346.06 0]
 [94657.16 145077.58 282574.31 2]
 [91749.16 114175.79 294919.57 1]
 [86419.7 153514.11 0.0 2]
 [76253.86 113867.3 298664.47 0]
 [78389.47 153773.43 299737.29 2]
 [73994.56 122782.75 303319.26 1]
 [67532.53 105751.03 304768.73 1]
 [77044.01 99281.34 140574.81 2]
 [64664.71 139553.16 137962.62 0]
 [75328.87 144135.98 134050.07 1]
 [72107.6 127864.55 353183.81 2]
 [66051.52 182645.56 118148.2 1]
 [65605.48 153032.0

In [5]:
#categorical encoding could lead us to wrong results as it can imply that one value could be greater than the other(not in this case)

#dummy encoding with oneHotEncoder
from sklearn.preprocessing import OneHotEncoder

#specify which column should be onehotencode category
onehotencoder = OneHotEncoder(categorical_features = [3])

#fit it to matrix X
X = onehotencoder.fit_transform(X).toarray()

In [6]:
#avoiding the dummy variable trap (not necessarily required)

#just removed the first column from X (talking all rows and take all the column starting form index 1)
X = X[:,1:]

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split

#1/3 of the dataset (10) will go in the test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 1/3, random_state = 0)

C:\Users\Nill\Miniconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [8]:
#fitting multiple linear regression to the training set

from sklearn.linear_model import LinearRegression

#creating object of LinearRegression class
regressor = LinearRegression()

#fit above object in our model
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
#predicting the test set results (creating a vector of predictions)
Y_pred = regressor.predict(X_test)

In [10]:
#predicted profits
print(Y_pred)
#real profits
print(Y_test)

[ 111616.64259452  132709.39466315  140155.11033792   76099.20398184
  186329.9424037   112822.19807255   63002.00394805   99107.10428092
  119287.75473382  175522.83864738  101000.698615     85772.99293235
  117713.76481526   90230.88085202  133375.04389451  167530.54765828
  158013.54602062]
[ 103282.38  144259.4   146121.95   77798.83  191050.39  105008.31
   81229.06   97483.56  110352.25  166187.94   96778.92   96479.51
  105733.54   96712.8   124266.9   155752.6   132602.65]


In [11]:
#building the optimal model using Backward Elimination

#process involved in backward eliminattion
#select a significance level to stay in the model (usually 0.05)
#fit the full model with all possible predictions
#consider the predictor with highest P-values (probability). if P>SL, go one step down, otherwise finish the model
#remove the predictor
#fit model agagin without this variable

#it consist of including all the Independect variable (IV) at first then removing one by one to find optimal IV
#the optimal independent variable(IV) team IV will IV that have high effect on dependent variable


In [12]:
import statsmodels.formula.api as sm

#add a column of 1 in the beginning of our matrix of feature X to include the constant be 0 in our MLR equation
#this is done to add a constant  b0 (column of all 1's) in the equation y = b0 + b1x1 + b2x2 + ..+bnXn
#in (50,1) 50 is the number of lines and 1 is the number of column
#axis = 0 is for adding it in a line and axis = 1 for a column

#here, we add a matrix of column 50 1's to X so its adds the column at the end but we need it in the beginning
# X = np.append(arr = X, values = np.ones((50,1)).astype(int), axis = 1)

#To add the column in beginning, we add the matrix X to the column of 50 1's
X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)

In [13]:
#creating optimal matirx of features

#Taking matirx of X with all its independent variable
X_opt = X[:,[0,1,2,3,4,5]]

#create a new regressor (object of new class of statsmodels library) and fit the regression to X_opt and Y
#endog = dependent vairable
#exog = array containing number of observations
regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()

In [14]:
#look for predictor with higher P (probability) value (table of p value; lower the p value, more significant IV will be)
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Tue, 12 Sep 2017   Prob (F-statistic):           1.34e-27
Time:                        09:44:07   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [16]:
#in the table, const are all the 1's column we added(index 0), x1 and x2 are the dummy variables (index 1 and 2),
#and rests are other amounts spent

#remove index of 2 (since it has a p-value of 0.990 which is  > SL of 0.05)
X_opt = X[:,[0,1,3,4,5]]

regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Tue, 12 Sep 2017   Prob (F-statistic):           8.49e-29
Time:                        09:48:25   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [17]:
#when removing over and over again, alwyas refer to original X feature matrix for getting index number

#remove index of 1 (since it has a p-value of 0.940 which is  > SL of 0.05)
X_opt = X[:,[0,3,4,5]]

regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Tue, 12 Sep 2017   Prob (F-statistic):           4.53e-30
Time:                        09:54:58   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [18]:
#since we alreday removed the first two columns, which were the dummy varibles, the new x1, x2 and 3 in the above table are
#R&D spent, admin spent and marketing spent

#remove index of 4 (since it has a p-value of 0.602 which is > SL of 0.05)
X_opt = X[:,[0,3,5]]

regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Tue, 12 Sep 2017   Prob (F-statistic):           2.16e-31
Time:                        09:59:22   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [19]:
#remove index of 5 (since it has a p-value of 0.060 which is > SL of 0.05)
X_opt = X[:,[0,3]]

regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Tue, 12 Sep 2017   Prob (F-statistic):           3.50e-32
Time:                        10:05:21   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
#we finally have only one independent variable (R&D spent) and that supposedly has a high statistical impact